import type { Metadata } from 'next';
import { Work_Sans, Spline_Sans_Mono } from 'next/font/google';
import clsx from 'clsx';
import './styles.css';

import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { DARK_TOKENS, LIGHT_TOKENS } from '@/constants';

const mainFont = Work_Sans({
  subsets: ['latin'],
  display: 'fallback',
  weight: 'variable',
  variable: '--font-family',
});
const monoFont = Spline_Sans_Mono({
  subsets: ['latin'],
  display: 'fallback',
  weight: 'variable',
  variable: '--font-family-mono',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const theme = 'light';

  return (
    <html
      lang='en'
      className={clsx(mainFont.className, monoFont.className)}
      data-color-theme={theme}
      // @ts-expect-error
      style={theme === 'light' ? LIGHT_TOKENS : DARK_TOKENS}
    >
      <body>
        <Header theme={theme} />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
